// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxovhfxwgwvllizczfib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4b3ZoZnh3Z3d2bGxpemN6ZmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjM1NDgsImV4cCI6MjA1ODgzOTU0OH0.OCuudqz5q6hB6c8dEA6Q9Y9nGp0tyEFOXpfrQuUgSXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);